### ISSUE TITLE
Implement a reference for the well known MIDI controller values

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_MIDI#10]
Implement something which can be used to retrieve the well known MIDI controller values, like mod wheel 1, global volume 7.

Needs to be done so it's optional and only loads in when the programmer wants it to avoid memory bloat.

**Comment by jepler** [comment]
Looks like #26 addressed this. Please feel free to comment or open a fresh issue if this is not the case.
