### ISSUE TITLE
Remove MIDI constructor defaults for midi_in and midi_out

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_MIDI#11]
A discussion has come up due to recent coding (in #3) and unintentional highlighting by `sphinx-build`-isms about the defaults for the `midi_in` and `midi_out` named parameters for the `MIDI` constructor. These two defaults have not changed (#9 does not change these values) and are present in the _current_ library:

```
    def __init__(self, midi_in=usb_midi.ports[0], midi_out=usb_midi.ports[1], *,
                 in_channel=None, out_channel=0, in_buf_size=30, debug=False):
```

There's also the question about wasting memory if the user is not using `usb_midi` as it will always be imported. Is `usb_midi` frozen in?

@sommersoft has queried what the best practice is here.

This was partly noticed because `sphinx-build` has started choking on this and that error is picked up by Travis. This appears to be due to a `sphinx-build` change/issue as this code has not changed since it last passed. Other code may be subject to this bug. Discussion on this: https://github.com/adafruit/Adafruit_CircuitPython_MIDI/pull/9#discussion_r271076883 and https://github.com/adafruit/Adafruit_CircuitPython_MIDI/pull/9#issuecomment-479693142

Reminder:
- fix up any example code to ensure they still work if this is changed,
- **_update any learn guides in conjunction with changes here_**, see below.

**TODO**s:

- [ ] Update guide: [Grand Central USB MIDI Controller in CircuitPython](https://learn.adafruit.com/grand-central-usb-midi-controller-in-circuitpython/overview) - this is probably best done in conjuction with updates required by #12

**Comment by tannewt** [comment]
I don't think these should be the default values. The midi library should be agnostic to the transport.

I think the signature should be:
```python
def __init__(self, *, midi_in=None, midi_out=None, in_channel=None, out_channel=0, in_buf_size=30, debug=False):
```

That would make `midi_in` and `midi_out` optional.

`usb_midi` is built-in so it won't impact memory use.

**Comment by kevinjwalters** [comment]
Did the code change to library. I'd suggest leaving this open until it's released and guide(s) are updated?

**Comment by kevinjwalters** [comment]
TODOs:

- [ ] Update guide: [Grand Central USB MIDI Controller in CircuitPython](https://learn.adafruit.com/grand-central-usb-midi-controller-in-circuitpython/overview) - this is probably best done in conjuction with updates required by #12

**Comment by kattni** [comment]
This appears to have been resolved.
