### ISSUE TITLE
Remove method based API for sending MIDI messages

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_MIDI#12]
#3 added an alternative message-centric `send()` interface. This could replace and supersede the existing method-based interface. The existing interface could be either left as is, re-implemented using the new messages or removed. Removal (briefly discussed on Discord with @tannewt) would:
1 reduce code and therefore memory (very useful for M0 boards),
2 force updates for at least one Adafruit Learn guide ([Grand Central USB MIDI Controller in CircuitPython](https://learn.adafruit.com/grand-central-usb-midi-controller-in-circuitpython/overview)),
3 likely to impact a few users using the existing interface.
4 #11 changes force minor updates to existing code so this may affect views on points 2 and 3 above.

https://github.com/adafruit/Adafruit_CircuitPython_MIDI/blob/master/examples/midi_simpletest2.py shows the two interfaces in use with same messages (events) for comparison.

**TODO**s:

- [ ] Update guide: [Grand Central USB MIDI Controller in CircuitPython](https://learn.adafruit.com/grand-central-usb-midi-controller-in-circuitpython/overview) - this is probably best done in conjuction with updates required by #11

**Comment by tannewt** [comment]
Hey, sorry for taking a while to get back to you. I'm for removing it from this library. Perhaps we should move it into a separate midi library. It will be better for conserving memory than the object oriented approach.

**Comment by jedgarpark** [comment]
Sounds good to me, thanks.

**Comment by CedarGroveStudios** [comment]
This is precisely where I was going with my version of the interface. Nicely done @kevinjwalters!

**Comment by kattni** [comment]
This has been resolved.

**Comment by kevinjwalters** [comment]
I had left this open because the guide has not been updated and I wasn't aware of anything else that would track that.
