### ISSUE TITLE
Setup ReadTheDocs

### ISSUE THREAD

**Issue by sommersoft** [adafruit/Adafruit_CircuitPython_MIDI#14]
It seems that ReadTheDocs was never setup for this library. Needs to be created, added as a subproject to circuitpython, and then added to the Bundle's `driver.rst` page.

**Comment by kevinjwalters** [comment]
I'm not familiar with this process, what needs to be setup here? I'm happy to do this if you can point me towards a comparable library that goes into https://circuitpython.readthedocs.io/projects/bundle/en/latest/

**Comment by kevinjwalters** [comment]
I see there is now a link on https://circuitpython.readthedocs.io/projects/bundle/en/latest/ to https://circuitpython.readthedocs.io/projects/midi/en/latest/ but that's currently (25-Oct-2019) broken?

**Comment by kattni** [comment]
This appears to be resolved.

**Comment by kevinjwalters** [comment]
Looks good to me.
