### ISSUE TITLE
midi.send() not transmitting message

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/Adafruit_CircuitPython_MIDI#15]
Consistently seeing this error when trying to execute a `midi.send()` message:
code:
`midi.send(NoteOn(msg.note, msg.velocity))`

error:
```Traceback (most recent call last):
  File "code.py", line 49, in <module>
  File "adafruit_midi/__init__.py", line 174, in send
  File "adafruit_midi/__init__.py, line 228, in _send
AttributeError: 'NoneType' object has no attribute 'write'
  
```
![image](https://user-images.githubusercontent.com/29906257/61243461-de1e2e00-a6fc-11e9-8004-29a05ae50e5b.png)

**Comment by tannewt** [comment]
What version of the library are you using and what is your complete code.py?

**Comment by CedarGroveStudios** [comment]
Ran some tests with the `midi_inoutdemo` example code and found an error I made when defining the UART instance. Working fine now. I'll close this issue.
