### ISSUE TITLE
Channel numbers in api could match the MIDI channel number

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_MIDI#2]
The current implementation of the `adafruit_midi` library uses the underlying protocol numbers for the API. The constructor does _not_ mention this in the docs but it is explained with an example in the `out_channel` property:

> out_channel(3) will send to MIDI channel 4

API users are likely to be more familiar with the actual channel numbers in product documentation and synthesizers. The api could handle the translation between midi channel number and its wire protocol representation for the user. This might reduce confusion and support queries about things not working when the wrong channel is used.

**Comment by ladyada** [comment]
yeah i was mixed about it - do you now if 'midi chan 1' == 0x0 is officially defined somewhere in the midi spex?

**Comment by kevinjwalters** [comment]
The full spec requires a login but there's a summary table on https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message which has a terse note:

> Channel Voice Messages [nnnn = 0-15 (MIDI Channel Number 1-16)] 

I just did a bit of menu diving on a Yamaha SY22 and it is configured with 1-16 range as I thought.

My MIDI experience is only recent and a bit limited. I see a few articles suggesting a few people have a more in depth and practical appreciation of it. Perhaps worth running past @jedgarpark and @CollinCunningham?

BTW, devices in OMNI mode will response to any channel so one needs to be careful with any practical tests here.

**Comment by kevinjwalters** [comment]
Semi-related, is the if test in `_generic_3()` ok? Should it be `if channel is not None:` ? And for consistency should that value also be ranged checked?

**Comment by kevinjwalters** [comment]
FYI, for anyone looking at this, there are existing guides/code _using_ (and explaining) this 0-15 numbering: https://learn.adafruit.com/grand-central-usb-midi-controller-in-circuitpython/code-usb-midi-in-circuitpython

**Comment by kevinjwalters** [comment]
I think it's too late to change this given it's already being distributed and _used_.
