### ISSUE TITLE
NoteOff does not return a note value

### ISSUE THREAD

**Issue by DyerMaker953** [adafruit/Adafruit_CircuitPython_MIDI#43]
Hi,

I'm trying to trigger LED lights on and off based on corresponding midi notes received.
I noticed when a NoteOn event is receive, the midi.receiver() captures a 'note' value, which I can use to identify the note/source. However, when NoteOff is received, there is no value assigned to 'note', and I'm unable to figure out how to tell which source generated the NoteOff signal.

Curious if this is intentional, or am I perhaps doing something incorrectly?

Thanks!

**Comment by tannewt** [comment]
It looks like it should work. Please post your test code and let us know what is generating the MIDI NoteOff message. Thanks!

**Comment by DyerMaker953** [comment]
Thanks for the quick reply! I've stripped down the code I'm using to make it a little simpler, but still replicate what I'm seeing.
I'm mostly working with a Roland TD-17 drum module, but also have a Korg Kross 2 keyboard which is having the same result.

If I run either of these devices through my computer into 'MidiView', I see notes specified for both NoteOn and NoteOff events.

I'm running my code on a Feather M4 Express using an rx/tx uart midi breakout board.

```
import board
import busio
import adafruit_midi

from adafruit_midi.note_off import NoteOff
from adafruit_midi.note_on import NoteOn
from adafruit_midi.midi_message import MIDIUnknownEvent

# Import MIDI
MIDI_channel = 10
uart = busio.UART(board.TX, board.RX, baudrate=31250, timeout=0.001)  # initialize UART
midi = adafruit_midi.MIDI(
    midi_out=uart, midi_in=uart, in_channel=MIDI_channel - 1, debug=False
    )

# Main Loop
while True:
    msg = midi.receive()

    if isinstance(msg, NoteOn) and msg.velocity != 0:
        print(msg.note, ":", msg.velocity, ":", msg.channel+1)
        

    elif (isinstance(msg, NoteOn) and msg.velocity == 0) or (isinstance(msg, NoteOff)):
        print(msg.note, ":", msg.velocity, ":", msg.channel+1)


    elif isinstance(msg, MIDIUnknownEvent) and msg.status != 254 and msg.status != 248:
        print("MIDIUnknownEvent:", msg.status)


```

**Comment by kevinjwalters** [comment]
`NoteOff` is currently broken, see #42
