### ISSUE TITLE
AttributeError: 'NoteOff' object has no attribute 'velocity'

### ISSUE THREAD

**Issue by touchgadget** [adafruit/Adafruit_CircuitPython_MIDI#47]
EDIT 2: No, still a problem with the program below but my longer program sort of works.

EDIT 1: SORRY, I updated to the 20211211 libraries and note-off velocity works fine!

This seems similar to #42. Changing velocity to _velocity works around the problem.

```
import time
import adafruit_midi
import usb_midi

from adafruit_midi.note_on import NoteOn
from adafruit_midi.note_off import NoteOff

MIDI = adafruit_midi.MIDI(midi_in=usb_midi.ports[0], midi_out=usb_midi.ports[1])

while True:
    msg = MIDI.receive()
    if isinstance(msg, NoteOn):
        print(time.monotonic(), 'Note-On', msg.channel, msg.note, msg.velocity)
    elif isinstance(msg, NoteOff):
        print(time.monotonic(), 'Note-Off', msg.channel, msg.note, msg.velocity)
```

**Comment by dhalbert** [comment]
Looks like `NoteOff` needs the same kind of fix as in https://github.com/adafruit/Adafruit_CircuitPython_MIDI/pull/44/files.

In your test program above, there is no `msg.velocity`, so that printing would fail.
