### ISSUE TITLE
MIDI controller number

### ISSUE THREAD

**Issue by coreyostman** [adafruit/Adafruit_CircuitPython_MIDI#5]
It looks like the documentation for control_change needs to be updated.

It says controller number must be 0-15. But that's not the case as MIDI accepts controller numbers from 0-127 and the underlying code definitely works, too. I've tested it with Apple Pro Logic X and it works fine for controller numbers > 15. Here's the MIDI 1.0 spec, btw:

https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2

It's important in order to handle 14-bit controls. For example, controller 20 is the MSB and controller 52 is the LSB. So by reading an analog input w/ high resolution, we can encode up to 14 bits and transmit over MIDI in two separate packets.

I'm using this on the Grand Central, btw. Wonderful board!

**Comment by ladyada** [comment]
could very well be - im not a musician :) do you want to try submitting a PR?

**Comment by coreyostman** [comment]
And although I've been coding since 1982, I'm new to Python and GitHub! :-) If there are some simple instructions you can point me to for submitting a PR, I definitely wouldn't mind learning. Otherwise, here's the diff:

diff adafruit_midi.py OLDadafruit_midi.py 
122c122
<         :param int control: The controller number. Must be 0-127.
---
>         :param int control: The controller number. Must be 0-15.

**Comment by ladyada** [comment]
you're never too old to learn - and this is a great learning opportunity (cause its not complex)

check out these guides:
https://learn.adafruit.com/an-introduction-to-collaborating-with-version-control
https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

try it :)

**Comment by coreyostman** [comment]
Thank you! I will definitely try it because I'd love to be involved.

**Comment by coreyostman** [comment]
Ok, I think I did it. :-) Please let me know if there's anything I should have done differently, and thanks so much for such wonderful products!!

**Comment by ladyada** [comment]
congrats on the pull request :) its merged

**Comment by ladyada** [comment]
@kattni plz bump :)

**Comment by kattni** [comment]
Done!
