### ISSUE TITLE
usb_midi lib not found

### ISSUE THREAD

**Issue by houserockr** [adafruit/Adafruit_CircuitPython_MIDI#54]
If I try to run the example provided in the readme page, I get

```
$ ./midi.py 
Traceback (most recent call last):
  File "/home/user/./midi.py", line 5, in <module>
    import usb_midi
ModuleNotFoundError: No module named 'usb_midi'
```

I installed with
`
$ sudo pip3 install adafruit-circuitpython-midi
`

Afterwards I also executed the `raspi-blinka.py` script and rebooted after that.

- OS is raspbian 11.7
- board is a rpi4b
- Python 3.9.2

The `usb_midi` lib is nowhere to be found. `pip_search` has no clue either.

**Comment by dhalbert** [comment]
`usb_midi` is a native (written in C) class in. When you try to use it on an RPi, you are using the Adafruit Blinka compatibility library, which does not emulate the `usb_midi` class or most of the other USB support. It _will_ work on, say, an RP2040 board, which is running native CircuitPython.
